name = "ci-api-backend"
compatibility_date = "2025-07-31"
account_id = "3313c43f8de986d6c7468be645fbb215"
main = "src/index.ts"

[vars]
ALLOWED_ORIGINS = "https://ci-static-frontend.daniels-331.workers.dev" 

[[kv_namespaces]]
binding = "ci_api_storage"
id = "f8236eb4e7104703b5ff128c39abb816"
preview_id = "f913b6731c7549f4b45e35ac45bb74ac"

